# example workflow for Black Duck scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: bd-sig-action
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  blackduck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Maven Build
      run: mvn -B -DskipTests package
    - name: Black Duck Full Scan
      if: ${{ github.event_name != 'pull_request' }}
      uses: synopsys-sig/synopsys-action@v1.5.0
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
        DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
        DETECT_EXCLUDED_DETECTOR_TYPES: 'GIT'
      with:
        blackduck_url: ${{ vars.BLACKDUCK_URL }}
        blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
        blackduck_scan_full: true
        blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #bridge_download_version: 0.1.272, 1.2.0
        ### Uncomment below configuration to enable automatic fix pull request creation if vulnerabilities are reported
        blackduck_fixpr_enabled: true
        blackduck_fixpr_maxCount: 5
        blackduck_fixpr_filter_severities: 'CRITICAL,HIGH'
        blackduck_fixpr_useUpgradeGuidance: 'SHORT_TERM,LONG_TERM'
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Mandatory when blackduck_fixpr_enabled is set to 'true'
        ### Uncomment below configuration if Synopsys Bridge diagnostic files needs to be uploaded
        include_diagnostics: true
    - name: Black Duck PR Scan
      if: ${{ github.event_name == 'pull_request' }}
      uses: synopsys-sig/synopsys-action@v1.5.0
      env:
        DETECT_BLACKDUCK_RAPID_COMPARE_MODE: ALL
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.base_ref }}
        DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.base_ref }}
        DETECT_EXCLUDED_DETECTOR_TYPES: 'GIT'
      with:
        blackduck_url: ${{ vars.BLACKDUCK_URL }}
        blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}      
        blackduck_scan_full: false
        blackduck_automation_prcomment: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #bridge_download_version: 0.1.272, 1.2.0
        include_diagnostics: true
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v3
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
